name: Trigger Update
on:
  workflow_dispatch:
  push:
    branches:    
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        repos: [test-frontend, test-frontend-two, non-existent]

    steps:
      - uses: actions/checkout@v1

      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.6.3
        with:
          owner: chylauSF
          repo: ${{ matrix.repos }}
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: update-knit-workflow.yml
