name: Trigger Update
on:
  push:

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: start-update
        uses: ./.github/actions/start-update
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
