name: Trigger Update
on:
  workflow_dispatch:
  push:
    branches:    
    - 'main'

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.6.3
        with:
          owner: chylauSF
          repo: test-frontend
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: update-knit-workflow.yml
